### ISSUE TITLE
你好 ，windows7 上， dll 加载不到

### ISSUE THREAD

**Issue by hr168** [Xutaotaotao/vite-react-electron-template#2]
如题， windows10 可以 ， windows7 上加载不到dll， 路径和顺序都是对的。 谢谢。

**Comment by Xutaotaotao** [comment]
具体报错什么

**Comment by hr168** [comment]
![81721871181_ pic](https://github.com/user-attachments/assets/a030155c-f212-4cdd-bec1-066bdb331590)
![91721871182_ pic](https://github.com/user-attachments/assets/b39a8ebe-5f7f-4987-8bd0-e93dc4d15a56)

dll 路径是有的，也正确。 window10 可以，win7 报这个错。 谢谢大佬回复。 

electron：22
node：16
electron-rebuilder:  最新的
koffi: 最新的

1，路径不包含中文

**Comment by Xutaotaotao** [comment]
贴一下引入DLL的地方的代码

**Comment by Xutaotaotao** [comment]
GitHub 主页加我微信 聊吧

**Comment by hr168** [comment]
🥲 是有些 ms 的系统库，没有包含进来。 template 脚手架没问题。
